spring.application.name=TeamProject2025

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/teamproject2025?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=hooby
spring.datasource.password=dev_taehyun1322!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update 
spring.mvc.hiddenmethod.filter.enabled=true
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework=DEBUG

# Email Authentication
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=${GMAIL_USERNAME}
#spring.mail.password=${GMAIL_APP_PASSWORD} // SMTP ? ?? ??? Gmail ? ????
spring.mail.username=kth132225@gmail.com
spring.mail.password=hwkztzudddcizdox
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000

# Redis for Email Authentication
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password= # ????? ??? ? ??? ???.
spring.data.redis.timeout=5000

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=TRACE

# updated_at 시간을 보니 시간대가 다르다는 것을 발견 -> UTC 설정의 문제였음 -> Asia/Seoul 로 시간 변경
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jackson.time-zone=Asia/Seoul

# AWS ElastiCache ? Redis ? ????? ???? ?????,
# Redis ? ?? VPC ? ??? ??? ??
# EC2 ? ?? ??? VPC ?? ??? ?????, local ?? VPC ? ?? ? ??
# ???, ?? ????? ??? ???? ???? ??? ? EC2 ? ????? ??,
# local redis ? ?? ???? ???? ??.

# Hibernate Validator에서 fail-fast 모드 활성화 (true: 첫 번째 유효성 검증 실패 시 즉시 예외 발생)
spring.validation.fail-fast=true

# Session Time
server.servlet.session.timeout=90m